assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE04OSPS-SF01B-4B-VELPTD106
stream:
  method: streamed
  name: velpt_user_configuration
workflow_config:
  schedule: 0 0 * * *
